#home:
#  path: /
#  defaults: { _controller: 'AppBundle\Controller\DefaultController::indexAction' }
#  methods:  GET
#

setupcheck:
    path: /api/setup-check
    controller: App\Controller\DefaultController::setupCheck

# API Routes
api_exchange_rates:
    resource: ../src/Controller/ExchangeRateController.php
    type: annotation
    prefix: /api

index:
    path: /{wildcard}
    defaults: {
        _controller: App\Controller\DefaultController::index
    }
    requirements:
        wildcard: .*
    # controller: App\Controller\DefaultController::index

